server:
  port: '3030'
  servlet:
    encoding:
      force: 'true'

spring:
  mvc:
    throw-exception-if-no-handler-found: 'true'
    async:
      request-timeout: '0'
  web:
    resources:
      add-mappings: 'false'

scripts:
  outputStream:
    capacity: '65536'
  executor:
    threadNamePrefix: 'script-exec-'
    corePoolSize: '10'
    maxPoolSize: '50'
    queueCapacity: '300'

