server:
  port: '3030'

webmvc:
  executor:
    corePoolSize: '20'
    maxPoolSize: '50'
    queueCapacity: '300'
    threadNamePrefix: 'mvc-exec-'

spring:
  mvc:
    throw-exception-if-no-handler-found: 'true'
    async:
      request-timeout: '0'
  resources:
    add-mappings: 'false'
  http:
    encoding:
      force: 'true'

scripts:
  outputStream:
    capacity: '65536'
  executor:
    threadNamePrefix: 'script-exec-'
    corePoolSize: '10'
    maxPoolSize: '50'
    queueCapacity: '300'

